language: node_js

node_js:
  - '14'

services:
  - docker

before_script:
  - npm install
  - chmod +x ./scripts/deploy.sh

cache:
  directories:
    - "node_modules"

script: npm test

after_success:
  - ./scripts/deploy.sh $HEROKU_AUTH_TOKEN

notifications:
  email:  false
