language: node_js

node_js:
  - '14'

services:
  - docker
  - mongodb

before_script:
  - npm install
  - npm run start-prod &

cache:
  directories:
    - "node_modules"

script: npm test

env:  
    secure: "o36GPRokM2hJdD/nb9qVkNM6EeNHwngemCBpyzNwHEIuCkUcJBFx+x05hntl9la+yWFZCoYr6/Eo4eDtJDVCeiDb/aOUA4YWIPH717juLzKxCx9uHvmOoH/A4fPbOKR+Jd2KWohMuIubAxluAqjvK5V8GyUzy0hPwjDbWxUOgv1zqAX3pMvx3zbZIqrmvWBM6KUCf2G2R1HRb/Rj2mge7EDUT97CB0BkM/qhHQJi7gt/U5FKm7CQJ5AwHACf1j3vV6708Hm+XUfydJffpqA2Ti2tuQeS1EXzbiTr7lxTBhgBKCRy3pVMovBRAfV4olVeyfBdvLC8PlOGKd4WJt2PneJg4EaKW2FIxgwbXCG7Lu0MZvWJuak77vbCTMjbpBsn5wq0NQNHYztgqaopKZ7JVuoTTL2hJTBKVDXxact3lB2ICi8s+SEW8KgNX3qtdIebNQe1OKYP+zwElZwrjJv8lo+gOgxdoXvziWBm+qcIlFA1Xk9yJETJlkTC0dOXwuBPbggMBOX6zprsdBsIaEObwEtZRlnnlQC7/jB8pxWDPOFi6JTlri0JsEwSt4Ko64sUhpEe41/NeKRTZzeLBdeaBhLNiQDa3cxvvBm6kRm9jf8tOdq2wBCHPCO5N8sQjBOmQn3CMqsficC7UxcJ0DPvKkaHb5/PtUHpF28sGgd5X9c="

after_success:
  - bash ./scripts/docker.sh 

deploy:
  provider: script
  script: bash ./scripts/deploy.sh $HEROKU_AUTH_TOKEN
  on:
    branch: main

notifications:
  email:  false