language: node_js

node_js:
  - '14'

services:
  - docker

before_script:
  - npm install

cache:
  directories:
    - "node_modules"

script: npm test

after_success:
  - bash ./scripts/docker.sh 

deploy:
  provider: script
  script: bash ./scripts/deploy.sh $HEROKU_AUTH_TOKEN

notifications:
  email:  false
